= AddressBook Level 4 - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/se-edu/addressbook-level4

By: `W12-2`      Since: `September 2018`       Licence: `MIT`

== Introduction

Debt Tracker (DT) is for those *who prefer to use a desktop app for tracking the user’s loans.*
DT has a mixed usage of *Command Line Interface (CLI) and a Graphical User Interface (GUI).*
For more basic commands, one may use CLI, but DT has also simplified potentially longer commands through the use of GUI.
DT can keep a record of your loans and debts as fast as other apps, if not faster!

== Quick Start

1. Ensure you have Java version 9 or later installed in your Computer.
2. Download the latest debttracker.jar.
3. Copy the file to the folder you want to use as the home folder for your Debt Tracker.
4. Double-click the file to start the app. The GUI should appear in a few seconds.
5. Type the command in the command box and press Enter to execute it. e.g. typing help and pressing Enter will open the help window.

Refer to Section 3, “Features” for details of each command.


[[Features]]
== Features

=== Adding a transaction : `add`

Adds a transaction to the database.
Format: add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS d/DEBT dl/DEADLINE [t/TAG]…​

=== Clearing all entries : `clear`

Clears all entries from the Debt Tracker.
Format: clear

=== Currency conversion of transaction amounts: `convert`

Converts the transaction amounts from their respective foreign currencies to Singapore Dollars.
Format: convert AMOUNT [MORE_AMOUNTS]

=== Deleting a transaction : `delete`

Deletes the specified transaction from the address book.
Format: delete INDEX

=== Editing a transaction : `edit`

Edits the fields of a particular transaction indentified by INDEX (must be a positive integer).
Format: edit INDEX [n/NAME] [p/PHONE] [e/EMAIL] [a/ADDRESS] [t/TAG]

=== Exiting the program : `exit`

Exits the program.
Format: clear

=== Filtering transactions: `filter`

Filter people out by whether they are a debtor or a creditor.
Format: filter [t/TAG]...

=== Locating transactions by transaction's name : `find`

Finds transactions exchanged with any transaction whose name contains any of the given keywords.
Format: find KEYWORD [MORE_KEYWORDS]

=== Viewing help : `help`

Invokes the user guide for handy reference when typing commands.
Format: `help`

=== Hiding transactions with a private contact : `hide`

Makes transactions exchanged with people tagged as private invisible. Can be toggled.
Format: hide n/NAME

=== Listing all recorded expenses : `history`

Lists all the commands that you have entered in reverse chronological order.

Lists all the expenses that you have recorded in the app, in reverse chronological order.
Format: history

=== Adding interest rate to a debt : `interest`

Adds an interest amount to all transactions based on the interest scheme and interest rate you input.
Format: interest INTEREST_SCHEME INTEREST_RATE

=== Redoing the previously undone command : `redo`

Reverses the most recent undo command.
Format: redo

=== Removing a debt : `remove`

Remove away a number of debts from one transaction recorded in the DT using click-and-drag.
The number of debts removed is up to the user’s selection.

=== Selecting a trasaction : `select`

Selects the transaction identified by the index number used in the displayed transaction list.
Format: select INDEX

=== Sorting transactions : `sort`

Sort people by the amount of money loaned to or from them, the deadlines of the debts
(be it whether you owe them or money or vice versa), or whether they are debtors or
creditors.
Format: sort [t/TAG]...

=== Undoing previous command : `undo`

Restores the address book to the state before the previous undoable command was executed. +
Format: undo

=== Updating a transaction : `update`

Edit an existing transaction’s details.
Format: edit INDEX [n/NAME] [p/PHONE] [e/EMAIL] [a/ADDRESS] [t/TAG]…​


=== Saving the data

Debt Tracker data is saved in the hard disk automatically after any command that changes the data. +

== FAQ

Q: How do I transfer my data to another Computer? +
A: Install the app in the other computer and overwrite the empty data file it creates with the file that contains the data of your previous Address Book folder.

== Command Summary

Add: add tt/TRANSACTION_TYPE ta/TRANSACTION_AMOUNT td/TRANSACTION_DEADLINE +
         n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS [t/TAG]…​ +
e.g. add tt/Loan ta/SGD 50.00 td/24/11/2018 n/James Ho p/22224444 e/jamesho@example.com a/123, Clementi Rd, 1234665 t/friend

Clear : clear

Convert: convert AMOUNT [MORE_AMOUNTS] +
e.g. convert USD 20.00  KRW 35.50  MYR 130.60

Delete : delete INDEX +
e.g. delete 3

Edit: edit INDEX [n/NAME] [p/PHONE] [e/EMAIL] [a/ADDRESS] [t/TAG]
e.g. edit 1 p/91234567 e/jondoe@example.com

Help : help

Hide : hide n/NAME +
e.g. hide n/Shawn

History : history

Interest: interest INTEREST_RATE INTEREST_SCHEME +
e.g. interest simple 1.1%

List : list

Filter: filter[t/TAG]... +
E.g. filter t/debtor

Find : find KEYWORD [MORE_KEYWORDS] +
e.g. find James Jake

Redo : redo

Select : select INDEX +
e.g.select 2

Sort: sort [t/TAG]... +
E.g. sort t/creditor

Undo : undo
