= AddressBook Level 4 - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/se-edu/addressbook-level4

By: `W12-2`      Since: `September 2018`       Licence: `MIT`

== Introduction

Debt Tracker (DT) is for those *who prefer to use a desktop app for tracking the user’s loans.*
DT has a mixed usage of *Command Line Interface (CLI) and a Graphical User Interface (GUI).*
For more basic commands, one may use CLI, but DT has also simplified potentially longer commands through the use of GUI.
DT can keep a record of your loans and debts as fast as other apps, if not faster!

[[Features]]
== Features

=== Viewing help : `help`

Invokes the user guide for handy reference when typing commands.

=== Adding a person: `add`

Adds a person to the Debt Tracker

=== Adding interest rate to a debt: interest

Adds an interest rate to a specific recorded debt for app to track.

=== Hiding a private contact : hide
Makes contacts tagged as private invisible. Can be toggled.


=== Editing a person : `edit`

Edits an existing person in the address book.

=== Locating persons by name: `find`

Finds persons whose names contain any of the given keywords.

=== Deleting a person : `delete`

Deletes the specified person from the address book.

=== Removing a debt : `remove`

Remove away a number of debts from one person recorded in the DT using click-and-drag.
The number of debts removed is up to the user’s selection.

=== Selecting a person : `select`

Selects the person identified by the index number used in the displayed person list.

=== Listing entered commands : `history`

Lists all the commands that you have entered in reverse chronological order.

=== Listing all recorded expenses: `log`

Creates a ledger of all the transactions that have been recorded. +

=== Undoing previous command : `undo`

Restores the address book to the state before the previous _undoable_ command was executed. +

=== Redoing the previously undone command : `redo`

Reverses the most recent `undo` command.

=== Clearing all entries : `clear`

Clears all entries from the Debt Tracker.

=== Exiting the program : `exit`

Exits the program.

=== Saving the data

Debt Tracker data is saved in the hard disk automatically after any command that changes the data. +

