= Debt Tracker - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/se-edu/addressbook-level4

By: `W12-2`      Since: `September 2018`       Licence: `MIT`

== Introduction

Debt Tracker (DT) is for those *who prefer to use a desktop app for tracking the user’s loans.*
DT has a mixed usage of *Command Line Interface (CLI) and a Graphical User Interface (GUI).*
For more basic commands, one may use CLI, but DT has also simplified potentially longer commands through the use of GUI.
DT can keep a record of your loans and debts as fast as other apps, if not faster!

== Quick Start

1. Ensure you have Java version 9 or later installed in your Computer.
2. Download the latest debttracker.jar.
3. Copy the file to the folder you want to use as the home folder for your Debt Tracker.
4. Double-click the file to start the app. The GUI should appear in a few seconds.
5. Type the command in the command box and press Enter to execute it. e.g. typing help and pressing Enter
   will open the help window.

Refer to Section 3, “Features” for details of each command.


[[Features]]
== Features

=== Viewing help : `help`

Invokes the user guide for handy reference when typing commands. +
Format: `help`

=== Adding a transaction : `add`

Adds a transaction to the database. +
Format: add tt/TRANSACTION_TYPE ta/TRANSACTION_AMOUNT td/TRANSACTION_DEADLINE +
n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS [t/TAG]…​

=== Uploading/Deleting a photo under a person : `uploadp`

May upload a photo to a person’s contact based on the index you input, or delete the photo from the index you input.
For both methods the first input after the command word should be the index of the contact whose photo you wish to
upload or delete.
For uploading a photo, the second input after the command word should be "up/" followed by the file path to the image
file.
For deleting a photo, the second input after the command word should be "up/" followed by the word "delete".

Formats:
To upload a photo: uploadp ind/[INDEX] up/[FILE_PATH]
To delete a photo: uploadp ind/[INDEX] up/delete

=== View calendar with debt deadlines : `calendar`

Displays a Google calendar showing the user's transactions and their deadlines.
This command can only be used with any one of the following keywords: show; login; logout.
This feature requires linking the deadlines to your Google account.

Formats:
To show calendar in the app: calendar show
To login to your Google account: calendar login
To logout of your Google account: calendar logout

=== Converting multiple currencies: `convert`

Converts amounts in multiple different foreign currencies to their respective amounts in +
the base currency, Singapore Dollars.
Format: convert FIRST_AMOUNT [MORE_AMOUNTS]

=== Calculating interest on transactions: `interest`

Calculates interest on transaction filtered by name(s) based on the interest rate provided.
Format: interest SCHEME INTEREST_RATE FIRST_NAME [MORE_NAMES]

=== Updating a transaction : `edit`

Edit an existing transaction’s details.
Format: edit INDEX [n/NAME] [p/PHONE] [e/EMAIL] [a/ADDRESS] [t/TAG]…​

=== Sorting transactions : `sort` (to be implemented)

Sort transactions by principal sum, deadline of payment or type of transactor (debtor/lender). +
Format: sort [t/TAG]...

=== Filtering transactions by name of person: `filter` (to be implemented)

Filter transactions by names of the contacts.
Format: filter FIRST_NAME [MORE_NAMES]

=== Filtering transactions by closest deadline: `nt`

Filtering and listing out the transaction(s) which deadlines are closest to the current date.
"nt" stands for NextTransaction.
Format: nt

=== Locating transactions by person's name : `find`

Finds transactions under a person whose name contains any of the given keywords.
Format: find NAME [MORE_NAMES]

=== Locating transactions by substring : `search`

Finds transactions under a person whose first name or last name contains the substring input by user.
Format: search SUBSTRING

=== Deleting a transaction : `delete`

Deletes the specified transaction from the address book.
Format: delete INDEX

=== Selecting a transaction : `select`

Selects the transaction identified by the index number used in the displayed transaction list.
Format: select INDEX

=== Listing all recorded expenses : `history`

Lists all the commands that you have entered in reverse chronological order.

Lists all the expenses that you have recorded in the app, in reverse chronological order.
Format: history

=== Analyzing a possible loan amount : `analytics`

Analyses the amount you have left after taking into consideration your loans, and the amount that you can loan out.
Format: analytics

=== Undoing previous command : `undo`

Restores the address book to the state before the previous undoable command was executed. +
Format: undo

=== Redoing the previously undone command : `redo`

Reverses the most recent undo command.
Format: redo

=== Clearing all entries : `clear`

Clears all entries from the Debt Tracker.
Format: clear

=== Exiting the program : `exit`

Exits the program.
Format: clear

=== Saving the data

Debt Tracker data is saved in the hard disk automatically after any command that changes the data. +

== FAQ

Q: How do I transfer my data to another Computer?
A: Install the app in the other computer and overwrite the empty data file it creates with the file that contains the data of your previous Address Book folder.

== Command Summary

Add : add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS d/DEBT dl/DEADLINE [t/TAG]…​
e.g. add n/James Ho p/22224444 e/jamesho@example.com a/123, Clementi Rd, 1234665  d/+500.00 dl/20 09 2019 t/friend t/colleague

//need to check
Uploadp : uploadp ind/INDEX up/FILE_PATH
e.g. uploadp ind/3 up/Users/Photo.png
OR: uploadp ind/INDEX up/delete
e.g. uploadp ind/1 up/delete

Calendar : calendar show
OR: calendar login
OR: calendar logout

Convert : convert FIRST_AMOUNT [MORE_AMOUNTS]
e.g. convert USD 20.00 AUD 35.40 MYR 152.60

Interest : int/INTEREST_RATE
e.g. int/1.10

Update : update INDEX [n/NAME] [p/PHONE_NUMBER] [e/EMAIL] [a/ADDRESS] d/DEBT dl/DEADLINE [t/TAG]…​
e.g. edit 2 n/James Lee e/jameslee@example.com

Sort : sort [t/TAG]...
E.g. sort t/creditor

Filter : filter[t/TAG]...
e.g. filter t/debtor

Nt (NextTransaction) : nt

Find : find KEYWORD [MORE_KEYWORDS]
e.g. find James Jake

Search : search SUBSTRING
e.g. search Be

Delete : delete INDEX
e.g. delete 3

Select : select INDEX
e.g.select 2

History : history

Analytics : analytics

Undo : undo

Redo : redo

Clear : clear

List : list

Help : help
